<?php
/**
 * Returns the current progress state for an enrichment job.
 * The main product-enrich.php endpoint writes progress to a temp JSON file
 * as it completes each step; the frontend polls this endpoint every 500 ms.
 *
 * GET param:  job_id  — the UUID generated by the frontend for this enrichment run
 *
 * Response:
 *   { "steps": { "brand_lookup": {"state":"done"}, "description": {"state":"active","label":"..."}, ... } }
 *   or {} when the job file doesn't exist yet / has already been cleaned up.
 */
require_once dirname(__FILE__) . '/../_config.php';

// Release the PHP session lock immediately — this file only reads a temp file
// and never writes session data. Without this, product-enrich.php's session
// lock blocks every poll request until the entire enrichment finishes.
session_write_close();

header('Cache-Control: no-cache, no-store');
header('Content-Type: application/json');

$job_id = preg_replace('/[^a-zA-Z0-9_\-]/', '', trim((string) ($_GET['job_id'] ?? '')));
if ($job_id === '') {
    echo json_encode(['steps' => []]);
    exit;
}

$file = BASE_PATH . 'public/tmp/enrichment/progress_' . $job_id . '.json';
if (!file_exists($file)) {
    echo json_encode(['steps' => []]);
    exit;
}

$data = json_decode(@file_get_contents($file), true);
echo json_encode(is_array($data) ? $data : ['steps' => []]);
